apiVersion: v1
kind: Pod
metadata:
  name: service-with-git-archivist
spec:
  restartPolicy: Always
  volumes:
  - name: repository-directory
    emptyDir: {}
  containers:
  - name: git-archivist
    image: sostheim/git-archivist:latest
    args: ["--v=2", "--logtostderr=true"]
    volumeMounts:
    - name: repository-directory
      mountPath: /.backup/
